services:
  postgres:
    image: postgres:16-alpine
    container_name: kindora-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kindora
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: kindora-network
